openapi: 3.0.0
info:
  title: CVE API
  version: 1.0.0
paths:
  /cve/{cve_id}:
    get:
      summary: Get CVE by ID
      parameters:
        - name: cve_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A CVE object
          content:
            application/json:
              schema:
                type: object
                properties:
                  CVE_ID:
                    type: string
                  Description:
                    type: string
                  Published_Date:
                    type: string
                    format: date-time
                  Last_Modified_Date:
                    type: string
                    format: date-time
                  Severity:
                    type: string
                example:
                  CVE_ID: "CVE-1999-0046"
                  Description: "Buffer overflow of rlogin program using TERM environmental variable."
                  Published_Date: "1997-02-06T05:00:00.000"
                  Last_Modified_Date: "2024-02-09T03:19:37.180"
                  Severity: "HIGH"
        '404':
          description: CVE not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                example:
                  error: "CVE not found"
  /cve/severity:
    get:
      summary: Get CVEs by Severity
      parameters:
        - name: severity
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of CVEs by severity
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Severity:
                      type: string
                    Count:
                      type: integer
                example:
                  - Severity: "LOW"
                    Count: 156
                  - Severity: "HIGH"
                    Count: 702
                  - Severity: "MEDIUM"
                    Count: 1140                
  /cve/top-impact:
    get:
      summary: Get Top 10 vulnerabilities by Impact Score
      responses:
        '200':
          description: Top 10 vulnerabilities by impact score
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    CVE_ID:
                      type: string
                    ImpactScore:
                      type: number
                      format: float
                example:
                  - CVE_ID: "CVE-1999-1144"	
                    ImpactScore: 10.0
                  - CVE_ID: "CVE-1999-0046"	
                    ImpactScore: 10.0
                  - CVE_ID: "CVE-1999-0067"	
                    ImpactScore: 10.0
                  - CVE_ID: "CVE-1999-0113"	
                    ImpactScore: 10.0
                  - CVE_ID: "CVE-2000-0141"	
                    ImpactScore: 10.0
                  - CVE_ID: "CVE-1999-1227"	
                    ImpactScore: 10.0
                  - CVE_ID: "CVE-1999-0426"	
                    ImpactScore: 10.0
                  - CVE_ID: "CVE-1999-1161"	
                    ImpactScore: 10.0
                  - CVE_ID: "CVE-1999-1139"	
                    ImpactScore: 10.0
                  - CVE_ID: "CVE-2001-0191"	
                    ImpactScore: 10.0
  /cve/top-exploitability:
    get:
      summary: Get Top 10 vulnerabilities by Exploitability Score
      responses:
        '200':
          description: Top 10 vulnerabilities by exploitability score
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    CVE_ID:
                      type: string
                    ExploitabilityScore:
                      type: number
                      format: float
                example:
                  - CVE_ID: "CVE-1999-0046"	
                    ExploitabilityScore: 10.0
                  - CVE_ID: "CVE-1999-0067"	
                    ExploitabilityScore: 10.0
                  - CVE_ID: "CVE-1999-0113"	
                    ExploitabilityScore: 10.0
                  - CVE_ID: "CVE-1999-0211"	
                    ExploitabilityScore: 10.0
                  - CVE_ID: "CVE-1999-0239"	
                    ExploitabilityScore: 10.0
                  - CVE_ID: "CVE-1999-0293"	
                    ExploitabilityScore: 10.0
                  - CVE_ID: "CVE-1999-0426"	
                    ExploitabilityScore: 10.0
                  - CVE_ID: "CVE-1999-0783"	
                    ExploitabilityScore: 10.0
                  - CVE_ID: "CVE-1999-0854"	
                    ExploitabilityScore: 10.0
                  - CVE_ID: "CVE-1999-1127"	
                    ExploitabilityScore: 10.0
  /cve/worst-products:
    get:
      summary: Get Worst Products
      responses:
        '200':
          description: Worst Products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    CVE_ID:
                      type: string
                    ExploitabilityScore:
                      type: number
                      format: float
                example:
                  - microsoft:	214
                  - debian:	183
                  - fedoraproject:	135
                  - canonical:	111
                  - redhat:	106
                  - linux:	100
  /cve/worst-platforms:
    get:
      summary: Get Worst Platforms
      responses:
        '200':
          description: Worst Platforms
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    CVE_ID:
                      type: string
                    ExploitabilityScore:
                      type: number
                      format: float
                example:
                  - debian_linux:	181
                  - fedora:	135
                  - ubuntu_linux:	111
                  - windows_10:	101
                  - linux_kernel:	100

